version: "3.8"

services:
  app:
    image: thuongtruong1009/boardly-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/app
    networks:
      - mongo_network
    ports:
      - 3000:3000
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://mongo/${DB_NAME}
    command: npm run start:docker

  mongo:
    image: mongo
    volumes:
      - ./.docker/mongo/data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo_network
    restart: unless-stopped

networks:
  mongo_network:
