version: "3.8"

services:
  app: &app
    image: thuongtruong1009/boardly-api:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    volumes:
      - .:/app
    networks:
      - mongo_network
      - nginx_network
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://mongo/${DB_NAME}
    command: npm run start:dev

  mongo:
    image: mongo
    build:
      target: production
    entrypoint:
      - /bin/sh
    ports:
      - 3000:${APP_PORT}
    environment:
      MONGO_URL: ${ATLAS_URL}
      NODE_ENV: production
    command:
      - -c
      - yarn start:prod

  app2:
    <<: *app

  nginx:
    container_name: nginx
    image: nginx:1.23.3-alpine
    ports:
      - ${APP_PORT}:80
    environment:
      - NGINX_HOST=127.0.0.1,localhost,0.0.0.0
      - NGINX_PORT=80
      - APP_HOST_1=app
      - APP_HOST_2=app2
      - APP_PORT=${APP_PORT}
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
    networks:
      - nginx_network
    depends_on:
      - app
      - app2
    restart: unless-stopped

networks:
  mongo_network:
  nginx_network:
